export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
SSH_KEY_PATH="~/.ssh/id_rsa"

# Check if zplug is installed
if [[ ! -d ~/.zgen ]]; then
    git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"
fi



autoload -Uz compinit
compinit

source "${HOME}/.zgen/zgen.zsh"

if ! zgen saved; then

    # zgen oh-my-zsh

    # oh-my-zsh plugins
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/command-not-found
    zgen oh-my-zsh plugins/z
    zgen oh-my-zsh plugins/ssh-agent

    # zsh plugins
    zgen load rimraf/k
    zgen load junegunn/fzf
    zgen load zsh-users/zsh-syntax-highlighting
    zgen load zsh-users/zsh-history-substring-search
    zgen load zsh-users/zsh-completions src

    # theme <3
    zgen load denysdovhan/spaceship-zsh-theme spaceship

    zgen save
fi

# theme settings
export SPACESHIP_PROMPT_SYMBOL="$"
export SPACESHIP_PACKAGE_SHOW=false

# zstyle
zstyle :omz:plugins:ssh-agent lifetime 4h

# load custom executable functions
for function in ~/.zsh/functions/*; do
  source $function
done

# asdf: king version manager
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# aliases
[[ -f ~/.aliases.zsh ]] && source ~/.aliases.zsh

# Local config
[[ -f ~/.zshrc_local.zsh ]] && source ~/.zshrc_local.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
