export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# GPG Rules All
export GPG_KEY_ID="0x9893F5557D7A9E22"
export GPG_SIGNING_KEY="0xD2090053C3686438"
export GPG_ENCRYPTION_KEY="0x83F5D16858E1FA5A"
export GPG_AUTHENTICATION_KEY="0xBF8701D1DEA3536B"
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpg-connect-agent updatestartuptty /bye
# gpgconf --launch gpg-agent

# Check if zplug is installed
if [[ ! -d ~/.zplug ]]; then
    git clone https://github.com/zplug/zplug ~/.zplug
    source ~/.zplug/init.zsh && zplug update --self
fi

# zplug init!
source ~/.zplug/init.zsh

zplug "zplug/zplug", hook-build:"zplug --self-manage"

# zsh plugins
zplug "rimraf/k"
zplug "junegunn/fzf", use:shell/key-bindings.zsh
zplug "zsh-users/zsh-syntax-highlighting"

# oh-my-zsh plugins
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/command-not-found", from:oh-my-zsh
zplug "plugins/z", from:oh-my-zsh

# theme <3
zplug denysdovhan/spaceship-zsh-theme, use:spaceship.zsh, from:github, as:theme

if ! zplug check; then
    zplug install
fi

zplug load

# theme <33
SPACESHIP_PROMPT_SYMBOL=$
SPACESHIP_PACKAGE_SHOW=false
SPACESHIP_KUBECONTEXT_SHOW=false
SPACESHIP_BATTERY_SHOW=false
SPACESHIP_PYENV_SHOW=false

# load custom executable functions
for function in ~/.zsh/functions/*; do
  source $function
done

# best version. manager. ever.
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.aliases.zsh ] && source ~/.aliases.zsh
[ -f ~/.zshrc_local.zsh ] && source ~/.zshrc_local.zsh

#AWSume alias to source the AWSume script
alias awsume=". ~/.pyenv/versions/2.7.10/bin/awsume"
